### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by mewmew** [mewmew/uc#6]
* [x] Introduction (issue #12)
* [x] Lexical Analysis (issue #7)
* [x] Syntactic Analysis (issue #8)
* [x] Semantic Analysis (issue #9)
* [ ] Intermediate Representation (issue #10) (*future ambition*)
* [x] IR Generation (issue #11)
* [x] Conclusion (issue #13)
